#server: finalserver3.c
#	gcc -o server finalserver2.c /home/root/iofunc/iolib.c `pkg-config --libs --cflags libmodbus`


serverled: serverled.c	
	gcc -o serverled serverled.c /home/root/iofunc/iolib.c `pkg-config --libs --cflags libmodbus`
